# Numpy

In [2]:
import numpy as np

In [14]:
a = np.array([_ for _ in range(10)])
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
type(a)

numpy.ndarray

In [11]:
#1차원의 10칸을 갖는 ndarray
a.shape

(10,)

In [15]:
ar2 = np.array([0.1,12,50,2,3.14])

In [16]:
#float로 통일됨
ar2

array([ 0.1 , 12.  , 50.  ,  2.  ,  3.14])

In [18]:
ar2.dtype

dtype('float64')

In [20]:
ar.dtype

dtype('int32')

In [21]:
x = np.array([1,2,3], dtype='f')

In [22]:
x.dtype

dtype('float32')

In [23]:
#인덱싱 가능
x[0]+x[1]

3.0

In [24]:
#U = 유니코드string
x = np.array([1,2,3], dtype='U')

In [25]:
x[0]+x[1]

'12'

In [26]:
x.dtype

dtype('<U1')

In [27]:
#리스트끼리는 나눌 수 없음
x = [0,1,-1,0]
y = [1,0,0,0]
x /y

TypeError: unsupported operand type(s) for /: 'list' and 'list'

In [28]:
#inf 는 무한대 nan = nor a number
xn = np.array(x)
yn= np.array(y)
xn/ yn

C:\Users\YOUR\AppData\Local\Temp\ipykernel_17200\1623060385.py:3: RuntimeWarning: divide by zero encountered in true_divide
  xn/ yn
C:\Users\YOUR\AppData\Local\Temp\ipykernel_17200\1623060385.py:3: RuntimeWarning: invalid value encountered in true_divide
  xn/ yn


array([  0.,  inf, -inf,  nan])

In [29]:
#백터화 연산
data = [_ for _ in range(10)]
answer = [_ *2 for _ in data]
print(answer)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]


In [30]:
x = np.array(data)
2 * x

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [37]:
c = np.array([[0,1,2],[3,4,5]])
c

array([[0, 1, 2],
       [3, 4, 5]])

In [7]:
a=np.array([[10,20,30,40],[50,60,70,80]])
a

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [9]:
d = np.array([[[1,2,3,4],
               [5,6,7,8],
               [9,10,11,12]],
              [[11,12,13,14],
               [15,16,17,18],
               [19,20,21,22]]])
d.shape
#(깊이,행,렬)

(2, 3, 4)

In [10]:
#차원의 크기
d.ndim

3

In [11]:
#리스트 인덱싱
test = [[1,2,3,4],[5,6,7,8]]
test[1][1]

6

In [21]:
#numpy array 인덱싱
a = np.array([[0,1,2],[3,4,5]])
a[0,2]

2

In [25]:
a=[[1,2,3,4],[5,6,7,8,]]
a[0][:3]

[1, 2, 3]

In [26]:
a = np.array([[0,1,2,3],[4,5,6,7]])
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [27]:
a[0,:]# 첫번째 행 전체

array([0, 1, 2, 3])

In [31]:
a[:,1] # 두번째 열 전체

array([1, 5])

In [32]:
a[1,1:]

array([5, 6, 7])

In [33]:
a[:2,:2]

array([[0, 1],
       [4, 5]])

In [189]:
m = np.array([[0,1,2,3,4],
              [5,6,7,8,9],
              [10,11,12,13,14]])

In [35]:
m[1,2]

7

In [36]:
m[2,-1]

14

In [37]:
m[1,1:3]

array([6, 7])

In [39]:
m[1:,2]

array([ 7, 12])

In [44]:
m[:2,3:]

array([[3, 4],
       [8, 9]])

In [45]:
#U4 ==> 4자리까지만 넣어짐
d = np.zeros(5, dtype="U4")
d

array(['', '', '', '', ''], dtype='<U4')

In [46]:
d[0] = 'abc'
d[1] = 'abcd'
d[2] = 'ABCDE'
d

array(['abc', 'abcd', 'ABCD', '', ''], dtype='<U4')

In [47]:
test = np.array([10,20,22])

In [49]:
#shape를 복사할때는 ones_like or zeros_like사용
np.ones_like(test, dtype='f')

array([1., 1., 1.], dtype=float32)

In [50]:
#np.empty로 빠르게 shape을 잡을 수 있다 
g= np.empty((4,3))
g

array([[4.24399158e-314, 8.48798317e-314, 1.27319747e-313],
       [1.69759663e-313, 2.12199579e-313, 2.54639495e-313],
       [2.54639495e-313, 2.97079411e-313, 3.39519327e-313],
       [3.81959242e-313, 4.24399158e-313, 4.66839074e-313]])

In [51]:
#Numpy버전의 range == arange
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
#0부터 100까지 11개의 선형적으로 분할한 위치 값을 출력
ex = np.linspace(0,100,11)
ex

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [55]:
#0부터 100까지 11개의 로그로 분할한 위치의 값을 출력합니다.(곡선형태)
ex = np.logspace(0,100,11)
ex

array([1.e+000, 1.e+010, 1.e+020, 1.e+030, 1.e+040, 1.e+050, 1.e+060,
       1.e+070, 1.e+080, 1.e+090, 1.e+100])

In [56]:
A = np.array([[1,2,3],[4,5,6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [57]:
#전치(transpose) 연산 ==> 행과 열을 바꾸는 작업
A.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [58]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [59]:
#reshape로 배열의 형태 변환
b = a.reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [62]:
ex = np.array(range(12))
ex

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [63]:
# -1을 쓰면 형태를 알아서 맞춰줌
ex.reshape(3,-1,2)

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [68]:
ex.reshape(2,3,-1)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [73]:
# 1차원으로 만들어줌(flatten, ravel)
ex.flatten
ex

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [74]:
x = np.arange(5)

In [78]:
x.shape

(5,)

In [76]:
#newaxis ==> 차원만 1차원 증가시킴
x[:, np.newaxis]

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [77]:
x.shape

(5,)

## 배열 연결(concatenate)
*hstack : 왼쪽에서 오른쪽으로 합침  
*vstack : 위에서 아래로 합침  
*dstack : 제3의 축(깊이)방향으로 배열 합침(차원 늘어남)  

In [84]:
a1 = np.ones((3,2))
a2 = np.zeros((3,3))
np.hstack([a1,a2])

array([[1., 1., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 0., 0., 0.]])

In [85]:
b1 = np.ones((2,3))
b2 = np.zeros((3,3))
np.vstack([b1,b2])

array([[1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [89]:
c1 = np.ones((3,4))
c2 = np.zeros((3,4))
c3 = np.empty((3,4))
np.dstack([c1,c2,c3])

array([[[1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.]],

       [[1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.]],

       [[1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.]]])

In [93]:
#3차원의 axis(축)으로 생각해야함
np.stack([c1,c2,c3], axis=0)

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [94]:
np.stack([c1,c2,c3], axis=1)

array([[[1., 1., 1., 1.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[1., 1., 1., 1.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[1., 1., 1., 1.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [95]:
np.stack([c1,c2,c3], axis=2)

array([[[1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.]],

       [[1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.]],

       [[1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.]]])

In [96]:
d1 = np.ones((4,5))
d2 = np.zeros((4,5))
d3 = np.arange(20).reshape(4,5)

In [97]:
d1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [98]:
d2

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [99]:
d3

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [112]:
np.stack([d1,d2,d3], axis=2)

array([[[ 1.,  0.,  0.],
        [ 1.,  0.,  1.],
        [ 1.,  0.,  2.],
        [ 1.,  0.,  3.],
        [ 1.,  0.,  4.]],

       [[ 1.,  0.,  5.],
        [ 1.,  0.,  6.],
        [ 1.,  0.,  7.],
        [ 1.,  0.,  8.],
        [ 1.,  0.,  9.]],

       [[ 1.,  0., 10.],
        [ 1.,  0., 11.],
        [ 1.,  0., 12.],
        [ 1.,  0., 13.],
        [ 1.,  0., 14.]],

       [[ 1.,  0., 15.],
        [ 1.,  0., 16.],
        [ 1.,  0., 17.],
        [ 1.,  0., 18.],
        [ 1.,  0., 19.]]])

In [110]:
print(np.stack([d1,d2,d3], axis=0).shape)
print(np.stack([d1,d2,d3], axis=1).shape)
print(np.stack([d1,d2,d3], axis=2).shape)

(3, 4, 5)
(4, 3, 5)
(4, 5, 3)


In [142]:
#np.r_ ==>배열을 axis 따라 좌우로 연결
np.r_[np.array([1,2,3]), np.array([4,5,6])]

array([1, 2, 3, 4, 5, 6])

In [115]:
#np.c_ ==> 배열의 차원을 증가시킨 후 좌우로 연결
np.c_[np.array([1,2,3]),np.array([4,5,6])]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [116]:
#tile은 동일한 배열을 반복하여 연결
a = np.array([[0,1,2],[3,4,5]])
np.tile(a,2)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [118]:
#4열3행을 각각 타일처럼 깔아줌
np.tile(a,(4,3))

array([[0, 1, 2, 0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5, 3, 4, 5],
       [0, 1, 2, 0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5, 3, 4, 5],
       [0, 1, 2, 0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5, 3, 4, 5],
       [0, 1, 2, 0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5, 3, 4, 5]])

In [138]:
a = np.zeros((3,3))
b = np.ones((3,2))
c = np.hstack([a,b])
d = np.arange(10,151,10).reshape(3,5)
e = np.vstack([c,d])
np.tile(e,(2,1))

array([[  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.]])

In [158]:
a2 = np.ones((3,3))
a1 = np.zeros((3,3))
print(a1)
print(a2)
print(np.r_[a1, a2])
print(np.hstack([a1,a2]))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0. 1. 1. 1.]
 [0. 0. 0. 1. 1. 1.]
 [0. 0. 0. 1. 1. 1.]]


## 브로드캐스팅

* 모양이 다른 배열 간의 연산이 가능하도록 배열의 크기를 변환시켜주는 것
* 넘파이 배열의 shape을 우측 정렬하고 각 차원별로 
* 브로드캐스팅이 가능하지 않을 때 ValueError발생

In [159]:
#스칼라 곱
a = np.array([1,2,3])
b = 2.0
a * b

array([2., 4., 6.])

In [160]:
#배열간 곱
a = np.array([1,2,3])
b = np.array([2,2,2])
a*b

array([2, 4, 6])

두 개의 연산과정은 같지만 스칼라 곱이 메모리를 적게 사용

ex) 깊이X행X열  
     A = 15X3X5   
     B = 깊이(x)3X1   
result = 15X3X5

## 차원 축소 연산

In [166]:
x = np.array([1,2,3,4])
np.sum(x)

10

In [165]:
x.sum()

10

In [167]:
x = np.arange(20).reshape(2,5,-1)
x

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

In [173]:
#해당 배열의 제일 작은 값의 인덱스를 반환, 연산 대상이 2차원 이상일때 axis 사용가능
x.argmin(axis=1)

array([[0, 0],
       [0, 0]], dtype=int64)

In [172]:
#해당 배열의 제일 큰 값의 결과를 반환, 연산 대상이 2차원 이상일때 axis 사용가능
x.max(axis=1)

array([[ 8,  9],
       [18, 19]])

In [175]:
#해당 배열의 제일 큰 값의 인덱스를 반환, 연산 대상이 2차원 이상일때 axis 사용가능
x.argmax(axis=0) # (0, 10), (1,11) 비교 

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]], dtype=int64)

In [176]:
x.argmax(axis=1) #(0,2,4,6,8) 비교 8의 인덱스 4반환

array([[4, 4],
       [4, 4]], dtype=int64)

In [177]:
x.argmax(axis=2) # (0,1), (2,3) 비교

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int64)

In [178]:
#평균
x.mean()

9.5

In [180]:
#중앙값
np.median(x)

9.5

In [182]:
#all은 배열 요소가 모두 True일때 True 반환
np.all([True,True,False])

False

In [183]:
#any는 배열 요수중 하나라도 True이면 True 반환
np.any([True,True,False])

True

In [187]:
a = np.zeros((100,100), dtype = np.int64)
np.any(a != 0)# a중 0이 아닌게 하나라도 있는가

False

In [186]:
np.all(a ==a)

True

In [188]:
practice = np.array([[1.1, 7.1, 8.0, 2.1, 6.5, 7.2],
                                [2.7, 5.2, 3.3, 9.0, 7.7, 2.8],
                                [0.7, 8.8, 4.2, 8.9, 4.3, 7.4],
                                [8.2, 1.1, 5.4, 2.9, 6.9, 0.2],
                                [7.4, 4.8, 2.7, 3.1, 2.8, 8.9]])

In [201]:
practice.max()

9.0

In [197]:
practice.sum(axis=0)

array([20.1, 27. , 23.6, 26. , 28.2, 26.5])

In [198]:
practice.max(axis=0)

array([8.2, 8.8, 8. , 9. , 7.7, 8.9])

In [199]:
practice.mean(axis=1)

array([5.33333333, 5.11666667, 5.71666667, 4.11666667, 4.95      ])

In [200]:
practice.min(axis=1)

array([1.1, 2.7, 0.7, 0.2, 2.7])

## 정렬

np.sort()는 객체 자료 자체변화(in-place)메서드이므로 사용에 주의 해아함

In [202]:
a = np.array([[4,3,5,7],
             [1,12,11,9],
             [2,15,1,14]])

In [203]:
np.sort(a)# axis=1과 동일

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2, 14, 15]])

In [204]:
np.sort(a,axis=0)

array([[ 1,  3,  1,  7],
       [ 2, 12,  5,  9],
       [ 4, 15, 11, 14]])

정렬하는게 아닌 순서만 알고 싶을 경우 argsort사용

In [209]:
b = np.array([42,38,12,25])
j = np.argsort(b)
j#값이 작은 순서대로 index 반환

array([2, 3, 1, 0], dtype=int64)

In [212]:
b[j]# 작은 순서대로 배열 가져올 수 있다!

array([12, 25, 38, 42])

## 고급 인덱싱

인덱스 배열을 사용한 인덱싱

In [214]:
a = np.array([[1,2],[3,4],[5,6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [218]:
print(a[[0,1,2],[0,1,0]]) #앞은 행의 대해서, 뒤는 열의 대해서 각각 매칭되어 값 호출

[1 4 5]


In [246]:
print(a[:,[0,1,0]]) # ==> :(a전체) 에서 행별로 [0,1,0]을 각각 가져온다

[[1 2 1]
 [3 4 3]
 [5 6 5]]


In [228]:
scores = np.array([[1,2,3,4],
                   [46,99,100,71],
                   [81,59,90,100]])

In [233]:
eng_rank = scores.argsort()[1]
eng_rank

array([0, 3, 1, 2], dtype=int64)

In [245]:
scores = np.array([[1,2,3,4],
                   [46,99,100,71],
                   [81,59,90,100]])
eng_rank = scores.argsort()[1]
scores[:, eng_rank]

array([[  1,   4,   2,   3],
       [ 46,  71,  99, 100],
       [ 81, 100,  59,  90]])

## 기술 통계

In [255]:
#표본 평균
np.mean(x)

9.5

In [256]:
#표본 분산
np.var(x)

33.25

In [257]:
#표준 편차
np.std(x)

5.766281297335398

In [258]:
#중앙값 == 가장 가운데에 있는 수 (짝수일경우 가운데 2개의 평균값)
np.median(x)

9.5

In [261]:
#사분위수
np.percentile(x,25)# 25분위 수 == 1사분위 수
np.percentile(x,50)#2사분위 수
np.percentile(x,75)#3사분위 수

4.75

## 난수 발생과 카운팅

In [ ]:
#파이썬의 random과 다름
np.random

### 시드

시드를 설정하면 random.rand의 숫자가 시드가 같으면 같은 숫자가 나옴

In [262]:
# 시드 설정하기
np.random.seed(0)

In [264]:
#다른 사람들이랑 같은 숫자 나옴(seed 0설정)
np.random.rand(5)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

### 데이터의 순서 바꾸기

In [265]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [267]:
np.random.shuffle(x)
x

array([3, 1, 8, 7, 9, 0, 6, 4, 2, 5])

### 데이터 샘플링

이미 있는 데이터 집합에서 일부를 무작위 선택하는것

In [269]:
np.random.choice(5,5, replace = False)#shuffle 명령과 같다

array([4, 2, 3, 1, 0])

In [270]:
np.random.choice(5,3, replace = False)#3개만 선택

array([2, 3, 4])

In [272]:
np.random.choice(5,10)#반복해서 10개 선택

array([0, 3, 0, 2, 3, 0, 1, 3, 3, 3])

In [274]:
np.random.choice(5,10, p=[0.1,0,0.3,0.6,0]) #선택 확률을 다르게 해서 10개 선택 1, 5는 확률 0, 3은 확률 60퍼라 많이나옴

array([0, 3, 3, 3, 3, 3, 2, 3, 3, 0])

### 난수 생성

* rand : 0부터 1사이의 균일 분포
* randn : 표준 정규 분포
* randint : 균일 분포의 정수 난수

In [276]:
#rand 함수는 0~1사이에서 균일한 확률 분포로 실수 난수를 생성
np.random.rand(3,5)

array([[0.20887676, 0.16130952, 0.65310833, 0.2532916 , 0.46631077],
       [0.24442559, 0.15896958, 0.11037514, 0.65632959, 0.13818295],
       [0.19658236, 0.36872517, 0.82099323, 0.09710128, 0.83794491]])

In [279]:
#randn 함수는 기댓값(mean)이 0, 표준편차가 1 인 표준정규분포를 따르는 난수 생성
np.random.randn(3,5)

array([[ 0.4253934 , -0.02797118,  1.47598983,  0.6467801 , -0.36433431],
       [-0.67877739, -0.35362786, -0.74074747, -0.67502183, -0.13278426],
       [ 0.61980106,  1.79116846,  0.17100044, -1.72567135,  0.16065854]])

In [280]:
#randint함수 ==> numpy.random.randint(low, high = None, size = None) high를 입력하지 않으면 0~low사이의 숫자를 입력하면 low~high사이의 숫자

In [281]:
np.random.randint(10,20, size=(3,5))

array([[16, 18, 12, 13, 10],
       [10, 16, 10, 16, 13],
       [13, 18, 18, 18, 12]])

In [296]:
np.random.seed(0)
x = np.random.randint(2, size=100)
print(sum(x==1)/len(x))

0.56


In [4]:
np.random.seed(0)
x = np.random.randint(1,7,100)
print(sum(x)/len(x))
print(x.mean())

3.42
3.42


### 정수 데이터 카운팅

unique() 함수는 데이터에서 중복된 값을 제거하고 중복되지 않는 값의 리스트를 출력합니다.  
return_counts 인수를 True 로 설정하면 각 값의 데이터 개수도 출력합니다.

In [298]:
np.unique([11,11,2,2,34,34])

array([ 2, 11, 34])

In [299]:
a = np.array(['a','b','b','c','a'])
index, count =np.unique(a, return_counts=True)

In [300]:
index

array(['a', 'b', 'c'], dtype='<U1')

In [301]:
count

array([2, 2, 1], dtype=int64)

In [297]:
#한번도 나오지 않은 값에 대해서도 출력하려면 bincount사용
np.bincount([1,1,2,2,2,3], minlength=6)# 1의 개수 2의 개수 3의 개수를 각각 구해줌

array([0, 2, 3, 1, 0, 0], dtype=int64)

# 실습 문제

In [10]:
a = np.arange(1,7).reshape(2,3)
b = np.arange(7,13).reshape(2,3)
a+b

array([[ 8, 10, 12],
       [14, 16, 18]])

In [11]:
a = np.arange(1,10)
a*3

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27])

In [17]:
a = np.zeros((1,10))
a[0,4] = 1
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [239]:
a = np.arange(1,50)
a[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [49]:
a = np.empty((3,3,3), dtype='U10')
a

array([[['', '', ''],
        ['', '', ''],
        ['', '', '']],

       [['', '', ''],
        ['', '', ''],
        ['', '', '']],

       [['', '', ''],
        ['', '', ''],
        ['', '', '']]], dtype='<U10')

In [51]:
np.full((3,3,3), 'Playdata')

array([[['Playdata', 'Playdata', 'Playdata'],
        ['Playdata', 'Playdata', 'Playdata'],
        ['Playdata', 'Playdata', 'Playdata']],

       [['Playdata', 'Playdata', 'Playdata'],
        ['Playdata', 'Playdata', 'Playdata'],
        ['Playdata', 'Playdata', 'Playdata']],

       [['Playdata', 'Playdata', 'Playdata'],
        ['Playdata', 'Playdata', 'Playdata'],
        ['Playdata', 'Playdata', 'Playdata']]], dtype='<U8')

In [56]:
a = np.arange(2,41,2).reshape(2,2,5)
a

array([[[ 2,  4,  6,  8, 10],
        [12, 14, 16, 18, 20]],

       [[22, 24, 26, 28, 30],
        [32, 34, 36, 38, 40]]])

In [63]:
np.eye(4, dtype='i')

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]], dtype=int32)

In [69]:
np.random.seed(0)
np.random.randint(2, size=(3,3)).astype(bool)

array([[False,  True,  True],
       [False,  True,  True],
       [ True,  True,  True]])

In [73]:
np.random.seed(0)
(np.random.rand(10) *10).astype(int)

array([5, 7, 6, 5, 4, 6, 4, 8, 9, 3])

In [112]:
a =np.ones((10,10))
a[[0,-1] ,:] =0
a[:,[0,-1]]=0
a

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [168]:
a = np.ones((8,8))
a[1::2,:]=0
a[:,1::2]=0
a[1::2,1::2] = 1
a

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

In [190]:
a = np.ones((8,8), dtype=int)
a[1::2,::2] = 0
a[::2,1::2] = 0
a

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

In [211]:
a = np.eye(2)
np.tile(a,(4,4))

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

In [220]:
a = np.arange(1,5)
even = np.array([True if i%2 ==0 else False for i in range(1,5)])
even

array([False,  True, False,  True])

In [217]:
a = np.arange(11)
minus = np.array([-1 if 3 < i < 7 else 1 for i in range(11)])
a * minus

array([ 0,  1,  2,  3, -4, -5, -6,  7,  8,  9, 10])

In [250]:
sum(np.arange(3,101,3))

1683

In [254]:
np.linspace(0.1,0.9,9)

array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [1]:
import numpy as np
while True:
    try:
        count = int(input("자연수를 입력해주세요"))
        if count <= 0:
            raise Error
        numbers = np.arange(1,46)
        lottos = [np.sort(np.random.choice(numbers,6,replace =False)) for _ in range(count)]
        display(lottos)
        break
    except:
        print("자연수를 입력해주세요")
    

자연수를 입력해주세요 3


[array([ 2, 12, 17, 37, 40, 45]),
 array([12, 13, 19, 26, 36, 41]),
 array([10, 15, 21, 23, 27, 43])]

In [1]:
import numpy as np
while True:
    try:
        num = int(input("자연수를 입력해주세요"))
        if num <= 0:
            raise Error
        nums= np.arange(1,46)
        lottos = np.sort(np.random.choice(nums,size=(num,6),replace =False))
        display(lottos)
        break
    except:
        print("자연수를 입력해주세요")

자연수를 입력해주세요 a


자연수를 입력해주세요


자연수를 입력해주세요 3


array([[ 9, 10, 21, 30, 41, 45],
       [ 8, 14, 22, 25, 29, 35],
       [ 4, 12, 16, 27, 28, 39]])

In [47]:
import numpy as np

while True:
    try:
        num = int(input("자연수를 입력해주세요"))
        if num <= 0:
            contunue
        print(np.random.choice(np.arange(1,46), size = (num,6) , replace =False))
        break
    except:
        print("자연수를 입력해주세요")

자연수를 입력해주세요 0


자연수를 입력해주세요


자연수를 입력해주세요 1


[[32 23  8 27 28  4]]


In [3]:
resp_time = np. array([158,  85, 205,  24,  42, 175, 188, 149, 153, 171, 137,  55, 108,
                       199, 177, 209, 218,  76, 103, 189, 110, 192, 136, 119,   4, 102,
                       177, 212, 110,  37, 163,  32,  77,  22, 125, 184,  46, 139,  72,
                       168, 133, 209, 148,  47, 102,  65, 160,  56,  11,  96, 169, 118,
                        55, 135, 217,  49, 100,  85, 179,  15, 139, 199, 124, 142,  15,
                        49, 168, 171, 168, 177, 147,  23, 199,  26,  51,  42,  90, 128,
                       186, 169, 129,  70, 198, 111,  81, 150,  17, 177, 201,  10,  75,
                       199,  55, 151, 183, 152, 119, 193, 110, 204])


In [7]:
a = (200 <= resp_time)
a

array([False, False,  True, False, False, False, False, False, False,
       False, False, False, False, False, False,  True,  True, False,
       False, False, False, False, False, False, False, False, False,
        True, False, False, False, False, False, False, False, False,
       False, False, False, False, False,  True, False, False, False,
       False, False, False, False, False, False, False, False, False,
        True, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False,  True, False,
       False, False, False, False, False, False, False, False, False,
        True])

In [44]:
print(np.percentile(resp_time,25))
print(np.percentile(resp_time,50))
print(np.percentile(resp_time,75))
print(np.quantile(resp_time, 0.25))

71.5
131.0
175.5
71.5


In [42]:
np.quantile(resp_time, 0.25)

71.5

In [110]:
p = ["뽀로로", "루피", "크롱"]
result = np.array([2, 1, 2, 2, 2, 2, 0, 2, 1, 1, 0, 0, 2, 0, 0, 1, 1, 2, 2, 2, 1, 1,
                   1, 2, 0, 2, 2, 0, 1, 1, 0, 2, 1, 0, 1, 2, 0, 0, 1, 0, 1, 1, 1, 2,
                   1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 2, 0, 2, 2, 0, 0, 1, 1, 1, 0, 0, 2,
                   2, 1, 0, 1, 2, 0, 2, 0, 0, 0, 2, 0, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0,
                   2, 0, 0, 0, 0, 2, 1, 2, 0, 2, 0, 0, 1, 0, 1, 2, 1, 2, 0, 2, 2, 1,
                   2, 0, 0, 1, 1, 0, 1, 2, 1, 2, 0, 2, 2, 2, 2, 0, 2, 2, 0, 2, 0, 2,
                   1, 1, 2, 1, 1, 0, 0, 1, 0, 0, 0, 2, 2, 0, 2, 0, 0, 0, 2, 0, 0, 0,
                   2, 0, 1, 2, 1, 0, 2, 0, 0, 1, 2, 1, 1, 2, 2, 0, 0, 0, 0, 2, 2, 1,
                   0, 1, 1, 2, 2, 1, 0, 0, 2, 0, 0, 0, 2, 0, 2, 2, 0, 2, 1, 0, 0, 2,
                   0, 1])
a = np.bincount(result,minlength =3)
print('{}가 {}표로 반장으로 선출되었습니다.'.format(p[a.argmax()],a.max()))

뽀로로가 81표로 반장으로 선출되었습니다.


In [10]:
p = ["뽀로로", "루피", "크롱"]
result = np.array([2, 1, 2, 2, 2, 2, 0, 2, 1, 1, 0, 0, 2, 0, 0, 1, 1, 2, 2, 2, 1, 1,
                   1, 2, 0, 2, 2, 0, 1, 1, 0, 2, 1, 0, 1, 2, 0, 0, 1, 0, 1, 1, 1, 2,
                   1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 2, 0, 2, 2, 0, 0, 1, 1, 1, 0, 0, 2,
                   2, 1, 0, 1, 2, 0, 2, 0, 0, 0, 2, 0, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0,
                   2, 0, 0, 0, 0, 2, 1, 2, 0, 2, 0, 0, 1, 0, 1, 2, 1, 2, 0, 2, 2, 1,
                   2, 0, 0, 1, 1, 0, 1, 2, 1, 2, 0, 2, 2, 2, 2, 0, 2, 2, 0, 2, 0, 2,
                   1, 1, 2, 1, 1, 0, 0, 1, 0, 0, 0, 2, 2, 0, 2, 0, 0, 0, 2, 0, 0, 0,
                   2, 0, 1, 2, 1, 0, 2, 0, 0, 1, 2, 1, 1, 2, 2, 0, 0, 0, 0, 2, 2, 1,
                   0, 1, 1, 2, 2, 1, 0, 0, 2, 0, 0, 0, 2, 0, 2, 2, 0, 2, 1, 0, 0, 2,
                   0, 1])
index, count =np.unique(result, return_counts=True)
print('{}가 {}표로 반장으로 선출되었습니다.'.format(p[count.argmax()],count.max()))

뽀로로가 81표로 반장으로 선출되었습니다.
